name: Go mod Lint
on: [workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.17"
      - run: go mod tidy
      - run: git diff --exit-code
      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v3.1.0
