name: Go Swagger Lint
on: [workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate server
        uses: docker://quay.io/goswagger/swagger
        with:
          options: --user root
          args: generate server -f swagger.yml -A ${{ github.event.repository.name }}
      - name: Generate client
        uses: docker://quay.io/goswagger/swagger
        with:
          options: --user root
          args: generate client -f swagger.yml -A ${{ github.event.repository.name }}
      - run: git diff --exit-code
