
name: NPM Build
on: [workflow_call]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  JS_PACKAGE_MANAGER: yarn
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: "^18"
          cache: 'npm'
      - name: Install Yarn
        run: npm install -g yarn
        if: env.JS_PACKAGE_MANAGER == 'yarn'
      - name: Build node
        env:
          CI: true
        run: |
          case $JS_PACKAGE_MANAGER in
            yarn)
              yarn install --frozen-lockfile
              ;;
            npm)
              npm ci
              ;;
            *)
              $JS_PACKAGE_MANAGER install
              ;;
          esac
          $JS_PACKAGE_MANAGER run lint
          git diff --exit-code
          $JS_PACKAGE_MANAGER test
          $JS_PACKAGE_MANAGER run build
      # - name: Run codacy-coverage-reporter
      #   uses: codacy/codacy-coverage-reporter-action@v1
      #   with:
      #     api-token: ${{ secrets.CODACY_API_TOKEN }}
      #     coverage-reports: coverage.out
      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        if: github.actor!= 'dependabot[bot]' # ignore the pull request which comes from user depbot.
