name: SQL to Go Lint
on: [workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello world action step
        uses: thecampagnards/sql-to-go@master
        with:
          sql-files: db/migrations/*.up.sql
          output-folder: internal/db
      - run: git diff --exit-code
