name: SQL to Go Lint
on: [workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://alpine
        with:
          args: ls -lah
      - uses: docker://ghcr.io/thecampagnards/sql-to-go:master
        with:
          args: -output-folder internal/db db/migrations/*.up.sql
      - run: git diff --exit-code
